/*DECLARANDO AS VARIAVEIS E PINOS TANTO DIGITAIS COMO ANALÓGICOS*/
int ldr = 0; //SENSOR (PINO ANALÓGICO 0)
int buzzer = 5; //BUZZER (PINO DIGITAL 5)
int Greenled =11; //LED VERDE (PINO DIGITAL 2)
int Yellowled = 10; //LED AMARELO (PINO DIGITAL 3)
int Redled = 9; //LED VERMELHO (PINO DIGITAL 4)
int vldr = 0; //VALOR INICIAL DA LUMINOSIDADE
int LuminosidadeLED; // Transforma a leitura em uma escala de 0 a 100

/*DECLARANDO A VARIAVEL BUZZER E DESATIVANDO ELA DE INÍCIO*/

/*DEFINE OS PINOS DE SAÍDA E ENTRADA*/
void setup() {
  pinMode(ldr, INPUT);
  pinMode(Greenled, OUTPUT);
  pinMode(Yellowled, OUTPUT);
  pinMode(Redled, OUTPUT);
  pinMode(buzzer, OUTPUT);
  Serial.begin(9600); //COMEÇA O SERIAL COM A VELOCIDADE DE 9600
}


/*ESTE CICLO UTILIZA CONDICIONAIS (if, else if, else) PARA 
GERAR OS INTERVALOS DE LUMINOSIDADE CORRESPONDENTES A 
CADA LED
OBS: ESTE CÓDIGO ATENDE SALTOS EXTREMOS DE LUMINOSIDADE
AINDA QUE A EFEITOS PRÁTICOS QUASE NUNCA OCORRAM,
ENTÃO UM SALTO DE LUMINOSIDADE BAIXA PARA MUITO ALTA E VICEVERSA
OCASIONADA EVENTUALMENTE POR UMA LANTERNA
TAMBÉM É ATENDIDA PELO CÓDIGO*/

void loop() {
  
  vldr=analogRead(ldr); //ATRIBUI  vldr O VALOR LIDO EM ldr
  
  if(vldr<800) {  //LUMINOSIDADE BAIXA
    digitalWrite(Greenled, HIGH); //LIGA O LED VERDE
    digitalWrite(Yellowled, LOW);
    digitalWrite(Redled, LOW);
  }
  
  else if(vldr>800 && vldr <=900) { //LUMINOSIDADE NORMAL
    digitalWrite(Yellowled, HIGH); //LIGA O LED AMARELO 
    digitalWrite(Greenled, LOW);
    digitalWrite(Redled, LOW);
    tone(buzzer, 1000, 100); // LIGA O BUZZER
    delay(100); //DELAY PARA MANTER O BUZZER LIGADO
    noTone(buzzer); //DESLIGA O BUZZER
    delay(100); //DELAY PARA MANTER O BUZZER LIGADO
    tone(buzzer, 1000, 100); // LIGA O BUZZER
    delay(100);  //DELAY PARA MANTER O BUZZER LIGADO
    noTone(buzzer); //DESLIGA O BUZZER
  }
  
  else { //LUMINOSIDADE MUITO ALTA
    digitalWrite(Redled, HIGH); // LIGA O LED VERMELHO
    digitalWrite(Yellowled, LOW);
    digitalWrite(Greenled, LOW);
    tone(buzzer, 600, 1000); // LIGA O BUZZER COM FREQUÊNCIA 600 POR 1 SEGUNDO
  }
  
  
  /*DELAY PARA COBRIR OSCILAÇÕES ABRUPTAS DE LUMINOSIDADE
  QUE OCORRAM ENTRE OS INTERVALOS DAS CONDICIONAIS*/
  delay(300); 
  
  /*CONTROLE DA LUMINOSIDADE NO SERIAL MONITOR*/
  Serial.println(vldr);
  /* MAPEIA A LEITURA PARA UMA ESCALA DE 0 a 100 */
  LuminosidadeLED = map(vldr, 49, 969, 0, 100);

  /* IMPRIME A INTENSIDADE DE LUZ */
  Serial.print("Intensidade de Luz: ");
  Serial.println(LuminosidadeLED);
}

/*O BUZZER É LIGADO POR UM TEMPO MAIOR DO QUE O TEMPO
PARA QUE O CICLO SE REPITA PARA COBRIR PEQUENAS OSCILAÇÕES
QUE POSSAM LIGAR E DESLIGAR O BUZZER RAPIDAMENTE*/


/*COMO O FOTORRESISTOR NÃO FORNECE UMA UNIDADE DE MEDIDA
MAS DETECTA A INTENSIDADE DE LUZ ATRAVÉS DA RESISTÊNCIA 
ELÉTRICA QUE VARIA DE ACORDO COM A QUANTIDADE DE LUZ INCIDENTE
SERIA PRECISO CONHECER E CALIBRAR O FOTORRESISTOR DE MODO A
GARANTIR QUE AS MEDIDAS COLOCADAS NA VARIÁVEL vldr
COINCIDAM COM AS PREFERÊNCIAS DE LUMINOSIDADE.*/
